---
title: "Ciudad de Buenos Aires"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
source("read_prono.R")
library(tidyverse)
library(data.table)
library(lubridate)
library(kableExtra)
library(patchwork)

loc1 <- setDT(loc1)
```

## Temperatura

Marcha de temperatura mínima y máxima en conjunto con las temperaturas observadas

```{r}
loc1 %>% 
  melt(measure.vars = c("tmax", "tmax_obs")) %>% 
  ggplot(aes(fecha_pronos, value)) +
  geom_point(aes(shape = variable), color = "red") +
  scale_shape(labels = c("Pronóstico", "Observación")) +
  facet_wrap(~validez_del_pronostico, 
             labeller = labeller(validez_del_pronostico = c("24" = "Validez 24 hs", 
                                                            "48" = "Validez 48 hs"))) +
  labs(x = "",
       y = "Temperatura máxima",
       shape = "") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  
 loc1 %>% 
  melt(measure.vars = c("tmin", "tmin_obs")) %>% 
  ggplot(aes(fecha_pronos, value)) +
  geom_point(aes(shape = variable), color = "blue") +
  scale_shape(labels = c("Pronóstico", "Observación")) +
  facet_wrap(~validez_del_pronostico, 
             labeller = labeller(validez_del_pronostico = c("24" = "Validez 24 hs", 
                                                            "48" = "Validez 48 hs"))) +
  labs(x = "",
       y = "Temperatura mínima",
       shape = "") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  patchwork::plot_layout(ncol = 1) 
```

Correlación.

```{r}
loc1 %>%
  melt(measure.vars = list(prono = c(tmax = "tmax", tmin = "tmin"), 
                           obs = c(tmax = "tmax_obs", tmin = "tmin_obs"))) %>% 
  ggplot(aes(obs, prono)) +
  geom_point(aes(color = factor(validez_del_pronostico))) +
  # geom_smooth(method = "lm", aes(color = factor(validez_del_pronostico))) +
  scale_color_manual(values = c("darkorange", rgb(0, 139, 139, maxColorValue = 255))) +
  facet_wrap(~variable, labeller = labeller(variable = c("1" = "Temperatura máxima",
                                                         "2" = "Tempetatura mínima")),
             scales = "free") +
  labs(x = "Observación", 
       y = "Pronóstico",
       color = "Validez") +
  theme_minimal() +
  theme(legend.position = "bottom")
```

### Estadísticas
```{r}
loc1 %>%
  melt(measure.vars = list(prono = c(tmax = "tmax", tmin = "tmin"), 
                           obs = c(tmax = "tmax_obs", tmin = "tmin_obs"))) %>% 
  .[, variable := if_else(variable == 1, "Temperatura máxima", "Temperatura mínima")] %>% 
  .[, .(bias = mean(prono - obs),
           mae = mean(abs(prono - obs)),
           rmse = sd(prono - obs)), by = .(validez_del_pronostico, variable)] %>% 
  kable(col.names = c("Validez", "Variable", "BIAS", "MAE", "RMSE"),
        align = "clccc",
        digits = 2) %>% 
  kable_styling(full_width = TRUE,
               bootstrap_options = c("responsive")) 
```

